-- MySQL Script generated by MySQL Workbench
-- 10/20/14 11:39:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `` INT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `CodigoCliente` INT NOT NULL,
  `Nombres` VARCHAR(45) NULL,
  `Apellidos` VARCHAR(45) NULL,
  `Edad` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`CodigoCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Administrador` (
  `CodigoAdministrador` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellidos` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `Administradorcol` VARCHAR(45) NULL,
  PRIMARY KEY (`CodigoAdministrador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ventas` (
  `CodigoVentas` INT NOT NULL,
  `codigoUsuario` INT NOT NULL,
  `fecha` VARCHAR(45) NULL,
  `CodigoAdministrador` INT NOT NULL,
  `CodigoCliente` INT NOT NULL,
  PRIMARY KEY (`CodigoVentas`),
  INDEX `CodigoCliente_idx` (`CodigoCliente` ASC),
  CONSTRAINT `CodigoCliente`
    FOREIGN KEY (`CodigoCliente`)
    REFERENCES `mydb`.`Clientes` (`CodigoCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CodigoAdm`
    FOREIGN KEY (`CodigoAdministrador`)
    REFERENCES `mydb`.`Administrador` (`CodigoAdministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Viajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Viajes` (
  `CodigoViaje` INT NOT NULL,
  `CodigoCliente` INT NOT NULL,
  `destino` VARCHAR(45) NULL,
  `hora_salida` VARCHAR(45) NULL,
  `hora_llegada` VARCHAR(45) NULL,
  PRIMARY KEY (`CodigoViaje`),
  INDEX `CodigoCliente_idx` (`CodigoCliente` ASC),
  CONSTRAINT `CodigoCliente`
    FOREIGN KEY (`CodigoCliente`)
    REFERENCES `mydb`.`Clientes` (`CodigoCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservaciones` (
  `codigoReser` INT NOT NULL,
  `CodigoCliente` INT NOT NULL,
  `fecha_Reservacion` VARCHAR(45) NULL,
  `horario` VARCHAR(45) NULL,
  PRIMARY KEY (`codigoReser`),
  INDEX `CodigoCliente_idx` (`CodigoCliente` ASC),
  CONSTRAINT `CodigoCliente`
    FOREIGN KEY (`CodigoCliente`)
    REFERENCES `mydb`.`Clientes` (`CodigoCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AutoBus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AutoBus` (
  `CodigoAutoBus` INT NOT NULL,
  `capacidad` VARCHAR(45) NULL,
  `Nombre_chofer` VARCHAR(45) NULL,
  `CodigoViaje` INT NOT NULL,
  PRIMARY KEY (`CodigoAutoBus`),
  INDEX `codigoViaje_idx` (`CodigoViaje` ASC),
  CONSTRAINT `codigoViaje`
    FOREIGN KEY (`CodigoViaje`)
    REFERENCES `mydb`.`Viajes` (`CodigoViaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Horarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Horarios` (
  `CodigoHorario` INT NOT NULL,
  `CodigoViaje` INT NOT NULL,
  `Tipo de Pago` VARCHAR(45) NULL,
  PRIMARY KEY (`CodigoHorario`),
  INDEX `codigoViaje_idx` (`CodigoViaje` ASC),
  CONSTRAINT `codigoViaje`
    FOREIGN KEY (`CodigoViaje`)
    REFERENCES `mydb`.`Viajes` (`CodigoViaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
